### ISSUE TITLE
Keyword `tilt` still not included everywhere

### ISSUE THREAD

**Issue by birnstiel** [richteague/imgcube#4]
https://github.com/richteague/imgcube/blob/295754b8f3b0889757f411b0c9f0b3b7efdd6092/imgcube/cube.py#L1361-L1368

On lines 1355 and 1362, the keyword `tilt` is passed to `disk_coords` which causes an error as this is not yet included (or shouldn't be passed)?

**Comment by richteague** [comment]
Ah that is an old parameter, it should be superseded by allowing negative inclinations.

**Comment by richteague** [comment]
I think that function needs some work. I wrote it a while ago but most of the bones should be there if you need it

**Comment by birnstiel** [comment]
yes, I just removed those `tilt=tilt` parts and now it works.

**Comment by richteague** [comment]
I've pushed a change which removes all the tilt parameters.
